stages:
  - build-deploy

build-deploy:
  stage: build-deploy
  only:
    - dev-deployment
  before_script:
    - docker compose --env-file /home/admin/adameds/.env.dev.payment down --rmi all
    - echo "@adameds:registry=https://gitlab.com/api/v4/groups/93029767/-/packages/npm/" >> .npmrc
    - echo "//gitlab.com/api/v4/groups/93029767/-/packages/npm/:_authToken=$AUTH_TOKEN" >> .npmrc
  script:
    - docker compose --env-file /home/admin/adameds/.env.dev.payment up -d