services:
  adameds-payment:
    build:
      context: ./
      dockerfile: Dockerfile
      no_cache: true
    container_name: adameds-payment
    image: adameds/payment-service:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: always
    environment:
      DOTENV_KEY: ${DOTENV_KEY}
      APP_MODE: ${APP_MODE}
    networks:
      - payment-network
    volumes:
      - type: bind
        target: /adameds-payment/.env.vault
        source: /home/gitlab-runner/adameds/.env.vault
networks:
  payment-network:
    driver: bridge